### PR TITLE
Broken1file

### PR DESCRIPTION
**Pull request by Monty**
In this one I just added "answers" to the end of words.js

### CODE REVIEW

**Comment by milsaware** [comment]
@Monty 

On line 42 of ```game.js``` try changing ```chosenWord = answers[rand];``` to ```chosenWord = answers[rand].toUpperCase();```

**Comment by Monty** [comment]
Works like magic! Thanks a lot for helping out. I’m a retired 76yo and JavaScript newbie. Wordled is really fun.

Now I can put a bunch of “answer” word lists in assets.js and simply switch among them by changing index.html.

I merged the fix into the branch foryoungkids, so I’ll delete the two “broken” branches.

Cheers,
Monty

**Comment by Monty** [comment]
Thanks again! I ran !fmt on answers.js so it’s easier to read/edit. I added “how to change” answers.js to the README.

I didn’t see a license on your code. Hope it’s OK to share my version with my friends who have grandkids. I’m not trying
To spread it widely, but you’re welcome to use my changes if they’re useful. 

Maybe I’ll get some other vocabulary lists from grandkids teachers. I’ll let you know what the kids think.

Cheers,
Monty

**Comment by milsaware** [comment]
Hi @Monty 

No problem, happy to help.

It's completely open source so you're free to edit, use and distribute the code in whatever manner you wish. Attribution is welcomed and appreciated, but not explicitly required.

I'm relatively new to Github so have to look into how to merge the repositories, but I like the edits, they add a different level to the game

**Comment by Monty** [comment]
I added an MIT LICENSE with ozboware.co.uk as the copyright holder.

It’s pretty much the standard license to allow others to use it with no restrictions.

I’m not well versed in Github projects with multiple contributors, but they should appear in the “Insights” section of any repositories online.
https://github.com/Monty/wordled/graphs/contributors

I merged your updates to my main and generated a pull request which should add it to your repo.

**Pull request closed without merging**
